//
// Module Timer_first_try.Timer_first_try_tb.struct
//
// Created:
//          by - User.UNKNOWN (VBOX)
//          at - 13:58:29 21.04.2023
//
// Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
//

`resetall
`timescale 1ns/10ps
module Timer_first_try_tb;


// Internal Declarations



// Local declarations

// Internal signal declarations
wire       alarm;
wire       clk;
wire [9:0] d;
wire [3:0] high;
wire       low;
wire       reset;
wire       start;
wire       stop;


// Instances 
Timer_first_try U_0( 
   .clk   (clk), 
   .d     (d), 
   .reset (reset), 
   .start (start), 
   .stop  (stop), 
   .alarm (alarm), 
   .high  (high), 
   .low   (low)
); 

Timer_first_try_tester U_1( 
   .alarm (alarm), 
   .high  (high), 
   .low   (low), 
   .clk   (clk), 
   .d     (d), 
   .reset (reset), 
   .start (start), 
   .stop  (stop)
); 


endmodule // Timer_first_try_tb

