//
// Test Bench Module quicksort_lib.verilog_qs_tb.verilog_qs_tester
//
// Created:
//          by - User.UNKNOWN (VBOX)
//          at - 21:15:00 18.05.2023
//
// Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
//
`resetall
`timescale 1ns/10ps
module verilog_qs_tb;


// Local declarations

// Internal signal declarations
reg        clk;
reg [10:0] in1;
reg [10:0] in2;
reg [10:0] in3;
reg [10:0] in4;
reg [10:0] in5;
reg [10:0] in6;
reg [10:0] in7;
reg [10:0] in8;
reg [10:0] in9;
reg [10:0] in10;
wire [10:0] out1;
wire [10:0] out2;
wire [10:0] out3;
wire [10:0] out4;
wire [10:0] out5;
wire [10:0] out6;
wire [10:0] out7;
wire [10:0] out8;
wire [10:0] out9;
wire [10:0] out10;


verilog_qs U_0(
   .clk   (clk),
   .in1   (in1),
   .in2   (in2),
   .in3   (in3),
   .in4   (in4),
   .in5   (in5),
   .in6   (in6),
   .in7   (in7),
   .in8   (in8),
   .in9   (in9),
   .in10  (in10),
   .out1  (out1),
   .out2  (out2),
   .out3  (out3),
   .out4  (out4),
   .out5  (out5),
   .out6  (out6),
   .out7  (out7),
   .out8  (out8),
   .out9  (out9),
   .out10 (out10)
);

verilog_qs_tester U_1(
   .clk   (clk),
   .in1   (in1),
   .in2   (in2),
   .in3   (in3),
   .in4   (in4),
   .in5   (in5),
   .in6   (in6),
   .in7   (in7),
   .in8   (in8),
   .in9   (in9),
   .in10  (in10),
   .out1  (out1),
   .out2  (out2),
   .out3  (out3),
   .out4  (out4),
   .out5  (out5),
   .out6  (out6),
   .out7  (out7),
   .out8  (out8),
   .out9  (out9),
   .out10 (out10)
);

always
begin
  assign in1 = 10;
end

endmodule // verilog_qs_tb


